import {
  User,
  Project,
  Program,
  Portfolio,
  Task,
  Goal,
  KeyResult,
  Risk,
  Issue,
  ChangeRequest,
  Timesheet,
  Budget,
  UserRole,
  ProjectStatus,
  RAGStatus,
  TaskStatus,
  Priority,
  RiskLevel,
  ChangeRequestStatus,
  TimesheetStatus,
  BudgetType,
} from '@/types'

// Mock Users
export const mockUsers: User[] = [
  {
    id: '1',
    tenantId: 'tenant-1',
    email: 'john.doe@company.com',
    firstName: 'John',
    lastName: 'Doe',
    role: UserRole.PROJECT_MANAGER,
    skills: [
      {
        id: '1',
        name: 'Project Management',
        level: 'EXPERT',
        category: 'Management',
      },
      { id: '2', name: 'Agile', level: 'ADVANCED', category: 'Methodology' },
    ],
    timezone: 'America/New_York',
    locale: 'en-US',
    status: 'ACTIVE',
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '2',
    tenantId: 'tenant-1',
    email: 'jane.smith@company.com',
    firstName: 'Jane',
    lastName: 'Smith',
    role: UserRole.TEAM_MEMBER,
    skills: [
      { id: '3', name: 'React', level: 'ADVANCED', category: 'Development' },
      {
        id: '4',
        name: 'TypeScript',
        level: 'ADVANCED',
        category: 'Development',
      },
    ],
    timezone: 'America/Los_Angeles',
    locale: 'en-US',
    status: 'ACTIVE',
    createdAt: new Date('2024-01-15'),
  },
  {
    id: '3',
    tenantId: 'tenant-1',
    email: 'mike.johnson@company.com',
    firstName: 'Mike',
    lastName: 'Johnson',
    role: UserRole.PMO_LEAD,
    skills: [
      {
        id: '5',
        name: 'Portfolio Management',
        level: 'EXPERT',
        category: 'Management',
      },
    ],
    timezone: 'Europe/London',
    locale: 'en-GB',
    status: 'ACTIVE',
    createdAt: new Date('2024-01-10'),
  },
]

// Mock Portfolios
export const mockPortfolios: Portfolio[] = [
  {
    id: 'portfolio-1',
    tenantId: 'tenant-1',
    name: 'Digital Transformation',
    description: 'Company-wide digital transformation initiative',
    ownerId: '3',
    status: RAGStatus.GREEN,
    budget: {
      id: 'budget-p1',
      entityId: 'portfolio-1',
      entityType: 'PORTFOLIO',
      type: BudgetType.CAPEX,
      currency: 'USD',
      totalBudget: 5000000,
      spentToDate: 2100000,
      committed: 1500000,
      forecast: 4800000,
      variance: 200000,
      categories: [
        { name: 'Labor', allocated: 3000000, spent: 1200000, percentage: 60 },
        { name: 'Software', allocated: 1500000, spent: 600000, percentage: 30 },
        {
          name: 'Infrastructure',
          allocated: 500000,
          spent: 300000,
          percentage: 10,
        },
      ],
      createdAt: new Date('2024-01-01'),
      updatedAt: new Date('2024-10-26'),
    },
    strategicGoals: [
      'Improve customer experience',
      'Increase operational efficiency',
    ],
    programs: [],
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-10-26'),
  },
]

// Mock Programs
export const mockPrograms: Program[] = [
  {
    id: 'program-1',
    tenantId: 'tenant-1',
    portfolioId: 'portfolio-1',
    name: 'Customer Portal Modernization',
    description: 'Modernize customer-facing portals and applications',
    ownerId: '3',
    status: RAGStatus.GREEN,
    startDate: new Date('2024-01-15'),
    endDate: new Date('2024-12-31'),
    budget: {
      id: 'budget-pg1',
      entityId: 'program-1',
      entityType: 'PROGRAM',
      type: BudgetType.CAPEX,
      currency: 'USD',
      totalBudget: 2000000,
      spentToDate: 800000,
      committed: 600000,
      forecast: 1900000,
      variance: 100000,
      categories: [
        {
          name: 'Development',
          allocated: 1200000,
          spent: 500000,
          percentage: 60,
        },
        { name: 'Design', allocated: 500000, spent: 200000, percentage: 25 },
        { name: 'Testing', allocated: 300000, spent: 100000, percentage: 15 },
      ],
      createdAt: new Date('2024-01-15'),
      updatedAt: new Date('2024-10-26'),
    },
    projects: [],
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-10-26'),
  },
]

// Mock Projects
export const mockProjects: Project[] = [
  {
    id: 'project-1',
    tenantId: 'tenant-1',
    programId: 'program-1',
    name: 'Customer Dashboard Redesign',
    description:
      'Complete redesign of the customer dashboard with modern UI/UX',
    code: 'CDR-001',
    status: ProjectStatus.IN_PROGRESS,
    ragStatus: RAGStatus.GREEN,
    ownerId: '1',
    managerId: '1',
    teamMembers: [
      {
        userId: '1',
        role: 'Project Manager',
        allocation: 50,
        joinedAt: new Date('2024-02-01'),
      },
      {
        userId: '2',
        role: 'Developer',
        allocation: 100,
        joinedAt: new Date('2024-02-01'),
      },
    ],
    startDate: new Date('2024-02-01'),
    endDate: new Date('2024-06-30'),
    plannedStartDate: new Date('2024-02-01'),
    plannedEndDate: new Date('2024-06-30'),
    budget: {
      id: 'budget-1',
      entityId: 'project-1',
      entityType: 'PROJECT',
      type: BudgetType.CAPEX,
      currency: 'USD',
      totalBudget: 500000,
      spentToDate: 250000,
      committed: 150000,
      forecast: 480000,
      variance: 20000,
      categories: [
        { name: 'Labor', allocated: 350000, spent: 175000, percentage: 70 },
        { name: 'Tools', allocated: 100000, spent: 50000, percentage: 20 },
        { name: 'Other', allocated: 50000, spent: 25000, percentage: 10 },
      ],
      createdAt: new Date('2024-02-01'),
      updatedAt: new Date('2024-10-26'),
    },
    progress: 55,
    tags: ['UI', 'Frontend', 'High Priority'],
    metadata: {},
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-10-26'),
  },
  {
    id: 'project-2',
    tenantId: 'tenant-1',
    programId: 'program-1',
    name: 'API Gateway Implementation',
    description: 'Implement new API gateway for microservices',
    code: 'AGI-002',
    status: ProjectStatus.IN_PROGRESS,
    ragStatus: RAGStatus.AMBER,
    ownerId: '1',
    managerId: '1',
    teamMembers: [
      {
        userId: '1',
        role: 'Project Manager',
        allocation: 30,
        joinedAt: new Date('2024-03-01'),
      },
    ],
    startDate: new Date('2024-03-01'),
    endDate: new Date('2024-08-31'),
    plannedStartDate: new Date('2024-03-01'),
    plannedEndDate: new Date('2024-08-15'),
    budget: {
      id: 'budget-2',
      entityId: 'project-2',
      entityType: 'PROJECT',
      type: BudgetType.CAPEX,
      currency: 'USD',
      totalBudget: 300000,
      spentToDate: 180000,
      committed: 80000,
      forecast: 310000,
      variance: -10000,
      categories: [
        { name: 'Labor', allocated: 200000, spent: 120000, percentage: 67 },
        {
          name: 'Infrastructure',
          allocated: 100000,
          spent: 60000,
          percentage: 33,
        },
      ],
      createdAt: new Date('2024-03-01'),
      updatedAt: new Date('2024-10-26'),
    },
    progress: 60,
    tags: ['Backend', 'Infrastructure', 'Critical'],
    metadata: {},
    createdAt: new Date('2024-03-01'),
    updatedAt: new Date('2024-10-26'),
  },
  {
    id: 'project-3',
    tenantId: 'tenant-1',
    name: 'Mobile App Development',
    description: 'New mobile application for iOS and Android',
    code: 'MAD-003',
    status: ProjectStatus.PLANNING,
    ragStatus: RAGStatus.GREEN,
    ownerId: '1',
    managerId: '1',
    teamMembers: [
      {
        userId: '1',
        role: 'Project Manager',
        allocation: 20,
        joinedAt: new Date('2024-10-01'),
      },
    ],
    startDate: new Date('2024-11-01'),
    endDate: new Date('2025-04-30'),
    plannedStartDate: new Date('2024-11-01'),
    plannedEndDate: new Date('2025-04-30'),
    budget: {
      id: 'budget-3',
      entityId: 'project-3',
      entityType: 'PROJECT',
      type: BudgetType.CAPEX,
      currency: 'USD',
      totalBudget: 600000,
      spentToDate: 0,
      committed: 0,
      forecast: 600000,
      variance: 0,
      categories: [
        { name: 'Labor', allocated: 450000, spent: 0, percentage: 75 },
        { name: 'Tools', allocated: 150000, spent: 0, percentage: 25 },
      ],
      createdAt: new Date('2024-10-01'),
      updatedAt: new Date('2024-10-26'),
    },
    progress: 5,
    tags: ['Mobile', 'iOS', 'Android'],
    metadata: {},
    createdAt: new Date('2024-10-01'),
    updatedAt: new Date('2024-10-26'),
  },
]

// Mock Tasks
export const mockTasks: Task[] = [
  {
    id: 'task-1',
    projectId: 'project-1',
    title: 'Design new dashboard layout',
    description: 'Create wireframes and mockups for the new dashboard',
    status: TaskStatus.DONE,
    priority: Priority.HIGH,
    assigneeId: '2',
    reporterId: '1',
    estimatedHours: 40,
    actualHours: 38,
    storyPoints: 8,
    startDate: new Date('2024-02-05'),
    dueDate: new Date('2024-02-20'),
    completedAt: new Date('2024-02-19'),
    tags: ['Design', 'UI'],
    checklist: [
      { id: '1', title: 'Research existing dashboards', completed: true },
      { id: '2', title: 'Create wireframes', completed: true },
      { id: '3', title: 'Review with stakeholders', completed: true },
    ],
    dependencies: [],
    attachments: [],
    comments: [],
    createdAt: new Date('2024-02-05'),
    updatedAt: new Date('2024-02-19'),
  },
  {
    id: 'task-2',
    projectId: 'project-1',
    title: 'Implement responsive navigation',
    description: 'Build responsive navigation component using React',
    status: TaskStatus.IN_PROGRESS,
    priority: Priority.HIGH,
    assigneeId: '2',
    reporterId: '1',
    estimatedHours: 24,
    actualHours: 18,
    storyPoints: 5,
    startDate: new Date('2024-03-01'),
    dueDate: new Date('2024-03-15'),
    tags: ['Development', 'Frontend'],
    checklist: [
      { id: '1', title: 'Setup component structure', completed: true },
      { id: '2', title: 'Add responsive breakpoints', completed: true },
      { id: '3', title: 'Write tests', completed: false },
    ],
    dependencies: [],
    attachments: [],
    comments: [],
    createdAt: new Date('2024-03-01'),
    updatedAt: new Date('2024-10-26'),
  },
  {
    id: 'task-3',
    projectId: 'project-1',
    title: 'Integrate charts and analytics',
    description: 'Add data visualization components for analytics',
    status: TaskStatus.TODO,
    priority: Priority.MEDIUM,
    assigneeId: '2',
    reporterId: '1',
    estimatedHours: 32,
    storyPoints: 8,
    dueDate: new Date('2024-11-15'),
    tags: ['Development', 'Analytics'],
    checklist: [],
    dependencies: [],
    attachments: [],
    comments: [],
    createdAt: new Date('2024-10-20'),
    updatedAt: new Date('2024-10-20'),
  },
  {
    id: 'task-4',
    projectId: 'project-2',
    title: 'Setup API Gateway infrastructure',
    description: 'Configure cloud infrastructure for API Gateway',
    status: TaskStatus.IN_PROGRESS,
    priority: Priority.CRITICAL,
    assigneeId: '1',
    reporterId: '1',
    estimatedHours: 16,
    actualHours: 12,
    storyPoints: 5,
    startDate: new Date('2024-03-05'),
    dueDate: new Date('2024-03-20'),
    tags: ['Infrastructure', 'DevOps'],
    checklist: [
      { id: '1', title: 'Provision cloud resources', completed: true },
      { id: '2', title: 'Configure security groups', completed: true },
      { id: '3', title: 'Setup monitoring', completed: false },
    ],
    dependencies: [],
    attachments: [],
    comments: [],
    createdAt: new Date('2024-03-05'),
    updatedAt: new Date('2024-10-26'),
  },
]

// Mock Goals/OKRs
export const mockGoals: Goal[] = [
  {
    id: 'goal-1',
    tenantId: 'tenant-1',
    level: 'COMPANY',
    title: 'Become the market leader in customer satisfaction',
    description: 'Achieve industry-leading customer satisfaction scores',
    ownerId: '3',
    quarter: 'Q4 2024',
    startDate: new Date('2024-10-01'),
    endDate: new Date('2024-12-31'),
    status: 'ACTIVE',
    keyResults: [
      {
        id: 'kr-1',
        goalId: 'goal-1',
        title: 'Increase NPS score from 45 to 65',
        type: 'NUMBER',
        startValue: 45,
        targetValue: 65,
        currentValue: 52,
        unit: 'points',
        weight: 40,
        confidence: 7,
        linkedInitiatives: ['project-1'],
        checkIns: [
          {
            id: 'ci-1',
            value: 52,
            confidence: 7,
            narrative: 'Good progress on new features',
            userId: '3',
            createdAt: new Date('2024-10-20'),
          },
        ],
        createdAt: new Date('2024-10-01'),
        updatedAt: new Date('2024-10-26'),
      },
      {
        id: 'kr-2',
        goalId: 'goal-1',
        title: 'Reduce customer support tickets by 30%',
        type: 'PERCENTAGE',
        startValue: 100,
        targetValue: 70,
        currentValue: 85,
        unit: '%',
        weight: 30,
        confidence: 8,
        linkedInitiatives: ['project-1', 'project-2'],
        checkIns: [],
        createdAt: new Date('2024-10-01'),
        updatedAt: new Date('2024-10-26'),
      },
    ],
    alignedGoals: [],
    createdAt: new Date('2024-10-01'),
    updatedAt: new Date('2024-10-26'),
  },
]

// Mock Risks
export const mockRisks: Risk[] = [
  {
    id: 'risk-1',
    projectId: 'project-2',
    title: 'API Gateway vendor lock-in',
    description:
      "Heavy dependency on specific cloud provider's API gateway could limit flexibility",
    category: 'TECHNICAL',
    probability: 3,
    impact: 4,
    score: 12,
    level: RiskLevel.HIGH,
    status: 'MITIGATING',
    ownerId: '1',
    mitigation: 'Design abstraction layer to minimize vendor-specific code',
    identifiedDate: new Date('2024-03-10'),
    reviewDate: new Date('2024-11-01'),
    createdAt: new Date('2024-03-10'),
    updatedAt: new Date('2024-10-26'),
  },
  {
    id: 'risk-2',
    projectId: 'project-1',
    title: 'Resource availability constraints',
    description: 'Key designer may not be available for full project duration',
    category: 'RESOURCE',
    probability: 4,
    impact: 3,
    score: 12,
    level: RiskLevel.HIGH,
    status: 'IDENTIFIED',
    ownerId: '1',
    mitigation: 'Cross-train team members on design tools',
    identifiedDate: new Date('2024-02-15'),
    createdAt: new Date('2024-02-15'),
    updatedAt: new Date('2024-10-26'),
  },
]

// Mock Issues
export const mockIssues: Issue[] = [
  {
    id: 'issue-1',
    projectId: 'project-2',
    title: 'Performance degradation in test environment',
    description: 'API response times exceeding SLA in test environment',
    severity: 'HIGH',
    status: 'IN_PROGRESS',
    ownerId: '1',
    reporterId: '2',
    slaHours: 24,
    escalationLevel: 1,
    identifiedDate: new Date('2024-10-20'),
    createdAt: new Date('2024-10-20'),
    updatedAt: new Date('2024-10-26'),
  },
]

// Mock Change Requests
export const mockChangeRequests: ChangeRequest[] = [
  {
    id: 'cr-1',
    projectId: 'project-1',
    title: 'Add dark mode support',
    description: 'Customer request to add dark mode theme to dashboard',
    requestedBy: '2',
    category: 'SCOPE',
    status: ChangeRequestStatus.UNDER_REVIEW,
    priority: Priority.MEDIUM,
    impact: {
      scope: 'New feature implementation',
      schedule: 14,
      cost: 25000,
    },
    justification:
      'Customer feedback indicates strong preference for dark mode',
    approvers: [
      { userId: '1', level: 1, status: 'APPROVED' },
      { userId: '3', level: 2, status: 'PENDING' },
    ],
    requestedDate: new Date('2024-10-15'),
    createdAt: new Date('2024-10-15'),
    updatedAt: new Date('2024-10-26'),
  },
  {
    id: 'cr-2',
    projectId: 'project-1',
    title: 'Increase server capacity',
    description: 'Scale infrastructure to handle 10x traffic growth',
    requestedBy: '1',
    category: 'RESOURCE',
    status: ChangeRequestStatus.APPROVED,
    priority: Priority.HIGH,
    impact: {
      scope: 'Infrastructure upgrade',
      schedule: 7,
      cost: 50000,
    },
    justification: 'Current system at 85% capacity, need headroom for growth',
    approvers: [{ userId: '3', level: 1, status: 'APPROVED' }],
    requestedDate: new Date('2024-10-10'),
    approvedDate: new Date('2024-10-12'),
    createdAt: new Date('2024-10-10'),
    updatedAt: new Date('2024-10-12'),
  },
  {
    id: 'cr-3',
    projectId: 'project-2',
    title: 'Add multi-language support',
    description: 'Internationalization for European markets',
    requestedBy: '3',
    category: 'SCOPE',
    status: ChangeRequestStatus.SUBMITTED,
    priority: Priority.MEDIUM,
    impact: {
      scope: 'Full localization framework',
      schedule: 21,
      cost: 35000,
    },
    justification: 'Expansion into EU markets requires multi-language support',
    approvers: [{ userId: '1', level: 1, status: 'PENDING' }],
    requestedDate: new Date('2024-10-20'),
    createdAt: new Date('2024-10-20'),
    updatedAt: new Date('2024-10-20'),
  },
  {
    id: 'cr-4',
    projectId: 'project-1',
    title: 'Extend project deadline',
    description: 'Request 2-week extension due to resource constraints',
    requestedBy: '2',
    category: 'SCHEDULE',
    status: ChangeRequestStatus.REJECTED,
    priority: Priority.LOW,
    impact: {
      schedule: 14,
    },
    justification:
      'Key developer on medical leave, need time to redistribute work',
    approvers: [{ userId: '1', level: 1, status: 'REJECTED' }],
    requestedDate: new Date('2024-10-05'),
    approvedDate: new Date('2024-10-06'),
    createdAt: new Date('2024-10-05'),
    updatedAt: new Date('2024-10-06'),
  },
  {
    id: 'cr-5',
    projectId: 'project-3',
    title: 'Security audit implementation',
    description: 'Implement recommendations from Q3 security audit',
    requestedBy: '1',
    category: 'QUALITY',
    status: ChangeRequestStatus.IMPLEMENTED,
    priority: Priority.CRITICAL,
    impact: {
      scope: 'Security hardening across platform',
      schedule: 10,
      cost: 45000,
    },
    justification: 'Critical security vulnerabilities identified in audit',
    approvers: [{ userId: '3', level: 1, status: 'APPROVED' }],
    requestedDate: new Date('2024-09-15'),
    approvedDate: new Date('2024-09-16'),
    implementedDate: new Date('2024-09-30'),
    createdAt: new Date('2024-09-15'),
    updatedAt: new Date('2024-09-30'),
  },
]

// Mock Timesheets
export const mockTimesheets: Timesheet[] = [
  {
    id: 'ts-1',
    userId: '2',
    weekStartDate: new Date('2024-10-21'),
    weekEndDate: new Date('2024-10-27'),
    status: TimesheetStatus.SUBMITTED,
    entries: [
      {
        id: 'tse-1',
        projectId: 'project-1',
        taskId: 'task-2',
        date: new Date('2024-10-21'),
        hours: 8,
        billable: true,
        description: 'Working on navigation component',
      },
      {
        id: 'tse-2',
        projectId: 'project-1',
        taskId: 'task-2',
        date: new Date('2024-10-22'),
        hours: 8,
        billable: true,
        description: 'Implementing responsive breakpoints',
      },
      {
        id: 'tse-3',
        projectId: 'project-1',
        taskId: 'task-2',
        date: new Date('2024-10-23'),
        hours: 6,
        billable: true,
        description: 'Testing navigation on mobile devices',
      },
      {
        id: 'tse-4',
        projectId: 'project-1',
        date: new Date('2024-10-24'),
        hours: 2,
        billable: false,
        description: 'Team meeting and planning',
      },
    ],
    totalHours: 24,
    submittedAt: new Date('2024-10-25'),
    createdAt: new Date('2024-10-21'),
    updatedAt: new Date('2024-10-25'),
  },
]

// Helper functions to get mock data
export const getMockUser = (id: string) => mockUsers.find((u) => u.id === id)
export const getMockProject = (id: string) =>
  mockProjects.find((p) => p.id === id)
export const getMockProgram = (id: string) =>
  mockPrograms.find((p) => p.id === id)
export const getMockPortfolio = (id: string) =>
  mockPortfolios.find((p) => p.id === id)
export const getMockTask = (id: string) => mockTasks.find((t) => t.id === id)
export const getMockGoal = (id: string) => mockGoals.find((g) => g.id === id)

// Mock API delay
export const mockApiDelay = () =>
  new Promise((resolve) => setTimeout(resolve, 300))
